config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, :only => [:create]
  end
  resources :blogs, :only => [:show, :index]
  resources :charges, :only => [:new, :create]
  
  root "posts#index"

  #get '/login' => 'sessions#new'
  get "/auth/:provider/callback", :to => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
end

app/models/blog.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :blog
  validates :content, presence: true
end

app/models/concerns/taggable.rb
module Taggable
extend ActiveSupport::Concern

  included do
    has_many :taggings
    has_many :tags, :through => :taggings
  end
  
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
 
  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Taggable
  has_many :comments
  belongs_to :user
  has_many :blogs
  
  validates :title, presence: true
  validates :body, presence: true
  mount_uploader :pic, PicUploader
  
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  mount_uploader :avatar, AvatarUploader
  def display_name
    name.blank? ? email : name
  end

  def self.authorize_with(auth)
    where(provider: auth["provider"], uid: auth["uid"]).first_or_create.tap do |u|
      u.name          = auth.info.name
      u.email_address = auth.info.email
      u.nickname      = auth.info.nickname
      u.access_token  = auth.credentials.token
      u.save!
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to root unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogController < ActionController::Base

  def index
    @posts = Post.all.order('created_at DESC').first(3)
    #@posts = Post.all.order('created_at DESC').first(3)
  end

  def show
    @post = Post.find_by_post_id(@post.id, :order => "created_at ASC")

  end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post }
        format.json { render json: { comment: render_to_string(@comment, formats: 'html') }}
      else
        format.html { redirect_to :back }
        format.json { render json: { error: "NOPE" } } # TODO actually do error here.
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :email_address, :name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :authorize, :except => [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC').first(3)
  end

  def new
    @post = Post.new
  end

  def show
    @posts = Post.all
    @comment = Comment.new
  end

  

  def create
    @post = Post.create(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :body, :all_tags, :pic)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.authorize_with(request.env["omniauth.auth"])
    if user 
      session[:user_id] = user.id
      redirect_to '/posts'
    else
      redirect_to '/login', :notice => "Fail."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/', :notice => "Signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :authorize
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email_address, :avatar, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post%></h2>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
  </div>
<% end %>

app/views/blogs/show.html.erb
<h1> show.html.erb </h1>

app/views/charges/create.html.erb
Thank you for donating $5.00!

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/comments/_comment.html.erb
<p class="comment">
  <%= comment.content %> <br>
  Comments by : <%= comment.name %> <br>
  Email : <%= comment.email_address %>
</p>

app/views/home/index.html.erb
<h1>New Post</h1>
 
<%= form_for :post, url: posts_path do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_field :body %><br>
  <br>
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %><br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
       
        <a class="navbar-brand" href="<%= root_path %>">Blog App</a>
      
      
       
      </div><!--/.navbar-collapse -->
    </div>
  </nav>

  <% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %><br>
  <%= link_to 'Donate', new_charge_path, class: "button round secondary small" %>
  <% else %>
  <%= link_to "Sign in with Github", "/auth/github" %><br>
  <% end %>
    
    <div class="row">
    <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_field :body %><br>
  <br>
  <%= f.label :tag %><br>
  <%= f.text_field :all_tags %><br>
  <br>
  <%= f.label :pic %><br>
  <%= f.file_field :pic %><br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="row">
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post%></h2>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
    <h5 class="all_tags">#<%= link_to post.all_tags %></h5>
    <p class="pic"><%= image_tag(post.pic.thumb) %></p>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_field :body %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %> 
  </h1>

  <p class="date">
      Submitted <%= time_ago_in_words(@post.created_at) %> Ago        
  </p>

  <p class="body">
    <%= @post.body %>
  </p>
  
  <p class="all_tags">
    # <%= @post.all_tags %>
  </p>

  <p class="pic">
    <%= image_tag(@post.pic.url) %>
  </p>
    <strong> Comments (<%= @post.comments.size %>):</strong>

    <div id="comment_list">
      <% @post.comments.each do |comment| %>
        <%= render comment %>
      <% end %>      
    </div>

    <%= form_for([@post, @comment]) do |f| %>
      Comment <%= f.text_area :content %> Name <br>
      <%= f.text_field :name %> Email address <br>
      <%= f.text_field :email_address %>  <br>
      <%= f.submit %>
    <% end %>
  </p>

  <%= link_to 'Home', posts_path %>
</div>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email_address %>
  Avatar: <%= f.file_field :avatar %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>